package me.aaron.dao.greenGen;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import java.util.ArrayList;
import java.util.List;

import me.aaron.dao.entity.ReceiverEntity;
import me.aaron.dao.entity.TaskEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "RECEIVER_ENTITY".
*/
public class ReceiverEntityDao extends AbstractDao<ReceiverEntity, Long> {

    public static final String TABLENAME = "RECEIVER_ENTITY";

    /**
     * Properties of entity ReceiverEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Status = new Property(0, int.class, "status", false, "STATUS");
        public final static Property Id = new Property(1, Long.class, "id", true, "_id");
        public final static Property TaskId = new Property(2, long.class, "taskId", false, "TASK_ID");
        public final static Property Uid = new Property(3, long.class, "uid", false, "UID");
        public final static Property Progress = new Property(4, float.class, "progress", false, "PROGRESS");
        public final static Property Username = new Property(5, String.class, "username", false, "USERNAME");
    };

    private DaoSession daoSession;

    private Query<ReceiverEntity> taskEntity_ReceiversQuery;

    public ReceiverEntityDao(DaoConfig config) {
        super(config);
    }
    
    public ReceiverEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"RECEIVER_ENTITY\" (" + //
                "\"STATUS\" INTEGER NOT NULL ," + // 0: status
                "\"_id\" INTEGER PRIMARY KEY ," + // 1: id
                "\"TASK_ID\" INTEGER NOT NULL ," + // 2: taskId
                "\"UID\" INTEGER NOT NULL ," + // 3: uid
                "\"PROGRESS\" REAL NOT NULL ," + // 4: progress
                "\"USERNAME\" TEXT);"); // 5: username
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"RECEIVER_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ReceiverEntity entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getStatus());
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(2, id);
        }
        stmt.bindLong(3, entity.getTaskId());
        stmt.bindLong(4, entity.getUid());
        stmt.bindDouble(5, entity.getProgress());
 
        String username = entity.getUsername();
        if (username != null) {
            stmt.bindString(6, username);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ReceiverEntity entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getStatus());
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(2, id);
        }
        stmt.bindLong(3, entity.getTaskId());
        stmt.bindLong(4, entity.getUid());
        stmt.bindDouble(5, entity.getProgress());
 
        String username = entity.getUsername();
        if (username != null) {
            stmt.bindString(6, username);
        }
    }

    @Override
    protected final void attachEntity(ReceiverEntity entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1);
    }    

    @Override
    public ReceiverEntity readEntity(Cursor cursor, int offset) {
        ReceiverEntity entity = new ReceiverEntity( //
            cursor.getInt(offset + 0), // status
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // id
            cursor.getLong(offset + 2), // taskId
            cursor.getLong(offset + 3), // uid
            cursor.getFloat(offset + 4), // progress
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // username
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ReceiverEntity entity, int offset) {
        entity.setStatus(cursor.getInt(offset + 0));
        entity.setId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setTaskId(cursor.getLong(offset + 2));
        entity.setUid(cursor.getLong(offset + 3));
        entity.setProgress(cursor.getFloat(offset + 4));
        entity.setUsername(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ReceiverEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ReceiverEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "receivers" to-many relationship of TaskEntity. */
    public List<ReceiverEntity> _queryTaskEntity_Receivers(long taskId) {
        synchronized (this) {
            if (taskEntity_ReceiversQuery == null) {
                QueryBuilder<ReceiverEntity> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.TaskId.eq(null));
                taskEntity_ReceiversQuery = queryBuilder.build();
            }
        }
        Query<ReceiverEntity> query = taskEntity_ReceiversQuery.forCurrentThread();
        query.setParameter(0, taskId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getTaskEntityDao().getAllColumns());
            builder.append(" FROM RECEIVER_ENTITY T");
            builder.append(" LEFT JOIN TASK_ENTITY T0 ON T.\"TASK_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected ReceiverEntity loadCurrentDeep(Cursor cursor, boolean lock) {
        ReceiverEntity entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        TaskEntity task = loadCurrentOther(daoSession.getTaskEntityDao(), cursor, offset);
         if(task != null) {
            entity.setTask(task);
        }

        return entity;    
    }

    public ReceiverEntity loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<ReceiverEntity> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<ReceiverEntity> list = new ArrayList<ReceiverEntity>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<ReceiverEntity> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<ReceiverEntity> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
