package me.aaron.dao.greenGen;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import me.aaron.dao.entity.TaskEntity;

import me.aaron.dao.entity.RemindEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "REMIND_ENTITY".
*/
public class RemindEntityDao extends AbstractDao<RemindEntity, Long> {

    public static final String TABLENAME = "REMIND_ENTITY";

    /**
     * Properties of entity RemindEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property RemindTime = new Property(1, int.class, "remindTime", false, "REMIND_TIME");
        public final static Property TaskId = new Property(2, long.class, "taskId", false, "TASK_ID");
    };

    private DaoSession daoSession;

    private Query<RemindEntity> taskEntity_RemindsQuery;

    public RemindEntityDao(DaoConfig config) {
        super(config);
    }
    
    public RemindEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"REMIND_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"REMIND_TIME\" INTEGER NOT NULL ," + // 1: remindTime
                "\"TASK_ID\" INTEGER NOT NULL );"); // 2: taskId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"REMIND_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, RemindEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getRemindTime());
        stmt.bindLong(3, entity.getTaskId());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, RemindEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getRemindTime());
        stmt.bindLong(3, entity.getTaskId());
    }

    @Override
    protected final void attachEntity(RemindEntity entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public RemindEntity readEntity(Cursor cursor, int offset) {
        RemindEntity entity = new RemindEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // remindTime
            cursor.getLong(offset + 2) // taskId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, RemindEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setRemindTime(cursor.getInt(offset + 1));
        entity.setTaskId(cursor.getLong(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(RemindEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(RemindEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "reminds" to-many relationship of TaskEntity. */
    public List<RemindEntity> _queryTaskEntity_Reminds(long taskId) {
        synchronized (this) {
            if (taskEntity_RemindsQuery == null) {
                QueryBuilder<RemindEntity> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.TaskId.eq(null));
                taskEntity_RemindsQuery = queryBuilder.build();
            }
        }
        Query<RemindEntity> query = taskEntity_RemindsQuery.forCurrentThread();
        query.setParameter(0, taskId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getTaskEntityDao().getAllColumns());
            builder.append(" FROM REMIND_ENTITY T");
            builder.append(" LEFT JOIN TASK_ENTITY T0 ON T.\"TASK_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected RemindEntity loadCurrentDeep(Cursor cursor, boolean lock) {
        RemindEntity entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        TaskEntity task = loadCurrentOther(daoSession.getTaskEntityDao(), cursor, offset);
         if(task != null) {
            entity.setTask(task);
        }

        return entity;    
    }

    public RemindEntity loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<RemindEntity> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<RemindEntity> list = new ArrayList<RemindEntity>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<RemindEntity> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<RemindEntity> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
